### PR TITLE
feat: prefer loaders by current files

### PR DESCRIPTION
**Pull request by SettingDust**

### CODE REVIEW

**Comment by juraj-hrivnak** [comment]
What's the purpose of the `RequestProjectInformation`?
Does this fix an issue or is it a refactor?

**Comment by SettingDust** [comment]
refactor I think. `RequestProjectInformation` is for wrapping the information. Or we need a `Map<String, List<String>` that hard to explain.

**Comment by juraj-hrivnak** [comment]
I don't understand. 😕 `RequestProjectInformation` is for wrapping info... but why is it needed?
Do project IDs need to be associated with loaders?

**Comment by SettingDust** [comment]
> I don't understand. 😕 `RequestProjectInformation` is for wrapping info... but why is it needed? Do project IDs need to be associated with loaders?

For finding the correspond loaders when requesting

**Comment by juraj-hrivnak** [comment]
I don't see the benefit of this refactor. `RequestProjectInformation` seems to be unneeded.

**Comment by SettingDust** [comment]
Then, how should I implement it to sort by project specified loaders order?

**Pull request closed without merging**
